name: "run command"
on:
  push:
  schedule:
    - cron: "50 14 ? * *" # JSTの23:50
  workflow_dispatch:

jobs:
  run:
    timeout-minutes: 10
    permissions: {}
    defaults:
      run:
        working-directory: ./prototype
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node env 🏗
        uses: actions/setup-node@v3.5.1
        with:
          cache: "yarn"
          cache-dependency-path: "prototype/yarn.lock"
      - name: Install dependencies
        run: yarn
      - name: Run command
        run: yarn dev
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DAILY_LOG_DATABASE_ID: ${{ secrets.NOTION_DAILY_LOG_DATABASE_ID }}
          NOTION_INTEGRATIONS_DATABASE_ID: ${{ secrets.NOTION_INTEGRATIONS_DATABASE_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
